// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

type Pos struct {
	ID            int64
	Name          string
	Location      string
	Description   string
	TotalSaleUnit int64
}
