// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Po struct {
	ID            int32
	Name          pgtype.Text
	Location      pgtype.Text
	Description   pgtype.Text
	TotalSaleUnit pgtype.Int4
}
