// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: pos.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPOS = `-- name: CreatePOS :one
INSERT INTO pos (
    name, location, description, total_sale_unit
) VALUES (
    $1, $2, $3, $4
) RETURNING id, name, location, description, total_sale_unit
`

type CreatePOSParams struct {
	Name          pgtype.Text
	Location      pgtype.Text
	Description   pgtype.Text
	TotalSaleUnit pgtype.Int4
}

func (q *Queries) CreatePOS(ctx context.Context, arg CreatePOSParams) (Po, error) {
	row := q.db.QueryRow(ctx, createPOS,
		arg.Name,
		arg.Location,
		arg.Description,
		arg.TotalSaleUnit,
	)
	var i Po
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.Description,
		&i.TotalSaleUnit,
	)
	return i, err
}

const deletePOS = `-- name: DeletePOS :exec
DELETE FROM pos
WHERE id = $1
`

func (q *Queries) DeletePOS(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePOS, id)
	return err
}

const getPOS = `-- name: GetPOS :one
SELECT id, name, location, description, total_sale_unit FROM pos
WHERE id = $1
`

func (q *Queries) GetPOS(ctx context.Context, id int32) (Po, error) {
	row := q.db.QueryRow(ctx, getPOS, id)
	var i Po
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.Description,
		&i.TotalSaleUnit,
	)
	return i, err
}

const listPOS = `-- name: ListPOS :many
SELECT id, name, location, description, total_sale_unit
FROM pos
LIMIT $1 OFFSET $2
`

type ListPOSParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListPOS(ctx context.Context, arg ListPOSParams) ([]Po, error) {
	rows, err := q.db.Query(ctx, listPOS, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Po
	for rows.Next() {
		var i Po
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Location,
			&i.Description,
			&i.TotalSaleUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePOS = `-- name: UpdatePOS :one
UPDATE pos
SET name = $2,
    location = $3,
    description = $4,
    total_sale_unit = $5
WHERE id = $1
RETURNING id, name, location, description, total_sale_unit
`

type UpdatePOSParams struct {
	ID            int32
	Name          pgtype.Text
	Location      pgtype.Text
	Description   pgtype.Text
	TotalSaleUnit pgtype.Int4
}

func (q *Queries) UpdatePOS(ctx context.Context, arg UpdatePOSParams) (Po, error) {
	row := q.db.QueryRow(ctx, updatePOS,
		arg.ID,
		arg.Name,
		arg.Location,
		arg.Description,
		arg.TotalSaleUnit,
	)
	var i Po
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.Description,
		&i.TotalSaleUnit,
	)
	return i, err
}
